<template>
  <main class="exam-take"><header><RouterLink to="/student">返回我的考试</RouterLink><span>人工智能在线考试</span><div class="header-actions"><span :class="['anti-cheat-state', { warning: antiCheatCount >= antiCheatLimit }]">防作弊：{{ antiCheatCount }}/{{ antiCheatLimit }} 次切屏</span><el-button size="small" @click="enterFullscreen">进入全屏</el-button></div></header>
    <section v-if="process" class="exam-shell"><div class="exam-state"><p class="page-eyebrow">答题中</p><h1>{{ process.stageName || '人工智能答题' }}</h1><div class="round"><strong>{{ answeredCount }}</strong><span>/ {{ process.aiMaxQuestionRounds || '-' }} 轮已完成</span></div><el-progress :percentage="progress" :show-text="false" :stroke-width="8" /><p class="safety-copy">切换标签页、窗口失焦、退出全屏等行为会被记录；达到次数上限后将转人工复核。</p></div>
      <template v-if="question"><article class="question-panel"><div class="question-labels"><span class="topic">{{ question.knowledgePoint || '综合知识' }}</span><span v-if="question.followUp" class="follow-up-label">针对上一题的追问</span></div><h2>{{ question.questionContent }}</h2><el-input v-model="answerContent" type="textarea" :rows="10" maxlength="5000" show-word-limit placeholder="请独立作答，尽量说明你的推理过程和关键结论。" :disabled="submitting" /><div class="answer-actions"><span v-if="lastFeedback">上一题反馈：{{ lastFeedback }}</span><el-button type="primary" :loading="submitting" :disabled="!answerContent.trim()" @click="submit">提交本题答案</el-button></div></article><aside class="records-panel"><h2>本阶段记录</h2><ol><li v-for="item in activeRecords" :key="item.id"><strong>第 {{ item.sequenceNo }} 轮<span v-if="item.previousRecordId" class="record-follow-up">追问</span></strong><span>{{ item.knowledgePoint }}</span><em v-if="item.averageScore !== null && item.averageScore !== undefined">{{ item.averageScore }} 分</em><small>{{ item.interviewerComment }}</small></li></ol></aside></template>
      <section v-else-if="inProgress && questionGenerationFailed" class="waiting"><h2>题目暂时无法生成</h2><p>系统会继续重试。请确认考试使用的人工智能接口已配置并可访问。</p><el-button @click="load(false)">重新加载</el-button></section>
      <section v-else-if="inProgress" class="waiting"><el-icon class="is-loading"><Loading /></el-icon><h2>正在准备下一题</h2><p>人工智能正在根据本轮答题情况生成题目，请保持当前页面。</p></section>
      <section v-else class="complete"><p class="page-eyebrow">{{ process.stageStatus === 'WAITING_APPROVAL' ? '待人工复核' : '已完成' }}</p><h2>{{ process.stageStatus === 'WAITING_APPROVAL' ? '答题已暂停' : '本次答题已完成' }}</h2><p>{{ process.processStatusView || '系统已保存答题结果。' }}</p><el-button type="primary" @click="goAnalysis">查看人工智能综合评价</el-button></section>
    </section>
    <section v-else class="waiting"><el-icon class="is-loading"><Loading /></el-icon><p>正在加载考试…</p></section>
  </main>
</template>

<script setup>
import { computed, onBeforeUnmount, onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { Loading } from '@element-plus/icons-vue'
import { RouterLink, useRoute, useRouter } from 'vue-router'
import { interviewApi } from '../services/api'

const route = useRoute(); const router = useRouter(); const processId = Number(route.params.processId); const process = ref(null); const question = ref(null); const records = ref([]); const answerContent = ref(''); const submitting = ref(false); const antiCheat = reactive({ switchCount: 0, hasEnteredFullscreen: false }); let timer = null; let heartbeatTimer = null; let antiCheatRetryTimer = null; let retryDelayMs = 2500; let disposed = false; let antiCheatSending = false; let lastSwitchReportAt = 0; const antiCheatQueue = []
const activeRecords = computed(() => process.value?.processStageId ? records.value.filter(item => Number(item.processStageId) === Number(process.value.processStageId)) : records.value)
const answeredCount = computed(() => activeRecords.value.filter(item => item.answerStatus === 'COMPLETED').length)
const progress = computed(() => process.value?.aiMaxQuestionRounds ? Math.min(100, Math.round(answeredCount.value / process.value.aiMaxQuestionRounds * 100)) : 0)
const inProgress = computed(() => process.value?.overallStatus === 'IN_PROGRESS' && process.value?.stageStatus === 'IN_PROGRESS')
const lastFeedback = computed(() => activeRecords.value.filter(item => item.interviewerComment).at(-1)?.interviewerComment || '')
const questionGenerationFailed = computed(() => activeRecords.value.some(item => item.questionStatus === 'FAILED'))
const antiCheatLimit = computed(() => Math.max(Number(process.value?.antiCheatSwitchLimit || 5), 1))
const antiCheatCount = computed(() => Math.max(Number(process.value?.antiCheatSwitchCount ?? antiCheat.switchCount), antiCheat.switchCount))
async function load(silent = false) { clearTimeout(timer); try { const [processResult, questionResult, recordResult] = await Promise.all([interviewApi.getIntervieweeProcess(processId), interviewApi.getNextAiQuestion(processId), interviewApi.listIntervieweeAiRecords({ processId })]); process.value = processResult.data; antiCheat.switchCount = Number(process.value?.antiCheatSwitchCount || 0); question.value = questionResult.data; records.value = recordResult.data || []; retryDelayMs = 2500; if (!question.value && inProgress.value) schedule() } catch (error) { if (!silent) ElMessage.error(error.message || '考试加载失败'); if (error.status !== 401) { schedule(retryDelayMs); retryDelayMs = Math.min(retryDelayMs * 2, 15000) } } }
function schedule(delay = 2500) { if (disposed) return; clearTimeout(timer); timer = window.setTimeout(() => load(true), delay) }
async function submit() { if (!question.value || !inProgress.value) return; submitting.value = true; try { await interviewApi.submitAiAnswer({ processId, questionId: question.value.id, answerContent: answerContent.value.trim() }); answerContent.value = ''; question.value = null; await load(true) } catch (error) { ElMessage.error(error.message || '提交失败，请重试') } finally { submitting.value = false } }
function shouldReportSwitch() { return inProgress.value }
function reportSwitchEvent(eventType, detail) { const now = Date.now(); if (now - lastSwitchReportAt < 1000 || !shouldReportSwitch()) return; lastSwitchReportAt = now; antiCheat.switchCount += 1; antiCheatQueue.push({ processId, eventType, detail, eventId: globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random().toString(36).slice(2)}`, occurredAtEpochMillis: now }); void flushAntiCheatQueue() }
async function flushAntiCheatQueue() { if (antiCheatSending || disposed || !antiCheatQueue.length) return; antiCheatSending = true; clearTimeout(antiCheatRetryTimer); try { while (!disposed && antiCheatQueue.length) { const response = await interviewApi.reportAntiCheatEvent(antiCheatQueue[0]); antiCheatQueue.shift(); if (response.data) { process.value = response.data; antiCheat.switchCount = Number(response.data.antiCheatSwitchCount || antiCheat.switchCount); if (response.data.stageStatus === 'WAITING_APPROVAL') question.value = null } } } catch (error) { if (!disposed) antiCheatRetryTimer = window.setTimeout(() => { void flushAntiCheatQueue() }, 2000) } finally { antiCheatSending = false } }
function handleFullscreenChange() { const wasFullscreen = antiCheat.hasEnteredFullscreen; antiCheat.hasEnteredFullscreen = document.fullscreenElement === document.documentElement; if (wasFullscreen && !antiCheat.hasEnteredFullscreen) reportSwitchEvent('FULLSCREEN_EXIT', '退出全屏') }
function handleVisibilityChange() { if (document.hidden) reportSwitchEvent('TAB_HIDDEN', '页面隐藏或切换标签页') }
function handleWindowBlur() { reportSwitchEvent('WINDOW_BLUR', '窗口失去焦点') }
function handleClipboardBlocked(event) { if (!inProgress.value) return; event.preventDefault(); reportAntiCheatEvent('CLIPBOARD_BLOCKED', `${event.type} 已拦截`) }
function reportAntiCheatEvent(eventType, detail) { if (disposed || !inProgress.value) return; antiCheatQueue.push({ processId, eventType, detail, eventId: globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random().toString(36).slice(2)}`, occurredAtEpochMillis: Date.now() }); void flushAntiCheatQueue() }
async function enterFullscreen() { try { if (!document.fullscreenElement) await document.documentElement.requestFullscreen(); antiCheat.hasEnteredFullscreen = true } catch (error) { reportAntiCheatEvent('FULLSCREEN_DENIED', error.message || '全屏授权失败'); ElMessage.warning('浏览器未允许全屏，切屏仍会被记录') } }
async function heartbeat() { if (!inProgress.value) return; try { const response = await interviewApi.heartbeat(processId); if (response.data) { process.value = response.data; if (response.data.stageStatus !== 'IN_PROGRESS') question.value = null } } catch { /* next load will surface an auth or network error */ } }
function goAnalysis() { router.push('/student') }
onMounted(() => { document.addEventListener('fullscreenchange', handleFullscreenChange); document.addEventListener('visibilitychange', handleVisibilityChange); window.addEventListener('blur', handleWindowBlur); document.addEventListener('copy', handleClipboardBlocked, true); document.addEventListener('cut', handleClipboardBlocked, true); document.addEventListener('paste', handleClipboardBlocked, true); document.addEventListener('drop', handleClipboardBlocked, true); antiCheat.hasEnteredFullscreen = document.fullscreenElement === document.documentElement; void load(); heartbeatTimer = window.setInterval(heartbeat, 20000) }); onBeforeUnmount(() => { disposed = true; clearTimeout(timer); clearTimeout(antiCheatRetryTimer); clearInterval(heartbeatTimer); document.removeEventListener('fullscreenchange', handleFullscreenChange); document.removeEventListener('visibilitychange', handleVisibilityChange); window.removeEventListener('blur', handleWindowBlur); document.removeEventListener('copy', handleClipboardBlocked, true); document.removeEventListener('cut', handleClipboardBlocked, true); document.removeEventListener('paste', handleClipboardBlocked, true); document.removeEventListener('drop', handleClipboardBlocked, true) })
</script>

<style scoped>
.exam-take{min-height:100vh;background:#f6f7f4}.exam-take>header{display:flex;justify-content:space-between;align-items:center;gap:14px;max-width:1180px;margin:0 auto;padding:20px 28px;border-bottom:1px solid var(--border);color:var(--text-muted);font-size:13px}.exam-take>header a{color:var(--primary);text-decoration:none}.header-actions{display:flex;align-items:center;gap:10px}.anti-cheat-state{color:var(--ink-soft);font-size:12px}.anti-cheat-state.warning{color:#b42318;font-weight:700}.exam-shell{display:grid;grid-template-columns:250px minmax(0,1fr) 260px;gap:24px;max-width:1180px;margin:0 auto;padding:34px 28px}.exam-state{padding:12px 0}.exam-state h1{margin:7px 0 30px;font-size:25px}.round{margin-bottom:10px}.round strong{font-size:38px}.round span{margin-left:6px;color:var(--text-muted);font-size:13px}.safety-copy{margin-top:20px;color:var(--text-muted);font-size:12px;line-height:1.6}.question-panel{padding:28px;border:1px solid var(--border);border-radius:var(--radius-sm);background:var(--surface)}.question-labels{display:flex;flex-wrap:wrap;gap:8px;align-items:center}.topic,.follow-up-label{display:inline-block;padding:4px 8px;font-size:12px;font-weight:700}.topic{background:var(--primary-soft);color:var(--primary)}.follow-up-label{background:#fff1dc;color:#9a5b00}.question-panel h2{margin:16px 0 24px;font-size:21px;line-height:1.6}.answer-actions{display:flex;justify-content:space-between;gap:16px;align-items:center;margin-top:16px}.answer-actions span{color:var(--text-muted);font-size:13px;line-height:1.55}.records-panel{padding:18px;border-left:1px solid var(--border)}.records-panel h2{margin:0 0 16px;font-size:16px}.records-panel ol{display:grid;gap:14px;margin:0;padding:0;list-style:none}.records-panel li{display:grid;gap:3px;padding-bottom:12px;border-bottom:1px solid var(--border)}.records-panel strong{font-size:13px}.records-panel span,.records-panel small{color:var(--text-muted);font-size:12px;line-height:1.5}.records-panel em{color:var(--primary);font-size:13px;font-style:normal}.record-follow-up{margin-left:7px;color:#9a5b00;font-size:11px}.waiting,.complete{max-width:720px;margin:90px auto;padding:44px;text-align:center;border:1px solid var(--border);border-radius:var(--radius-sm);background:var(--surface)}.waiting .el-icon{font-size:28px;color:var(--primary)}.complete h2{margin:8px 0}.complete p:not(.page-eyebrow),.waiting p{color:var(--text-muted);line-height:1.7}@media(max-width:980px){.exam-shell{grid-template-columns:1fr}.exam-state{padding:0}.records-panel{border-left:0;border-top:1px solid var(--border)}.exam-take>header,.exam-shell{padding-left:16px;padding-right:16px}}@media(max-width:560px){.exam-take>header{align-items:flex-start;flex-wrap:wrap}.header-actions{margin-left:auto}.answer-actions{flex-direction:column;align-items:stretch}.question-panel{padding:20px}.waiting,.complete{margin:40px 16px;padding:28px}}
</style>
