<template>
  <main class="student-page"><header class="student-head"><div><p class="page-eyebrow">学生考试</p><h1>我的考试</h1><p>{{ session.displayName }}，请在开放时间内完成考试。</p></div><div class="head-actions"><RouterLink to="/student/register">切换学生</RouterLink><el-button @click="logout">退出</el-button></div></header>
    <section><div class="section-head"><h2>可参加的考试</h2><el-button :loading="loading" @click="load">刷新</el-button></div><div v-if="exams.length" class="exam-grid"><article v-for="exam in exams" :key="exam.id" class="exam-item"><div class="exam-meta"><span>{{ exam.className || '全体学生' }}</span><span>{{ exam.questionRounds }} 轮</span></div><h3>{{ exam.examName }}</h3><p>{{ exam.instructions || '请根据题目要求独立完成答题。' }}</p><dl><div><dt>及格分</dt><dd>{{ exam.passingScore }}</dd></div><div><dt>开放时间</dt><dd>{{ dateText(exam.publishStart) }}{{ exam.publishEnd ? ` - ${dateText(exam.publishEnd)}` : '' }}</dd></div></dl><el-button type="primary" :loading="startingId === exam.id" @click="start(exam)">{{ exam.processId ? '继续答题' : '开始考试' }}</el-button></article></div><div v-else class="empty-state">当前没有开放的考试。</div></section>
    <section class="attempts"><div class="section-head"><h2>答题记录与学习分析</h2></div><div v-if="attempts.length" class="attempt-list"><article v-for="attempt in attempts" :key="attempt.processId" class="attempt-item"><div><h3>{{ attempt.examName }}</h3><p>{{ attempt.statusView || stateText(attempt) }}</p><span>{{ dateText(attempt.startedAt) }}</span></div><div class="score"><strong>{{ attempt.scoreRate ?? 0 }}%</strong><span>得分率</span></div><div class="score"><strong>{{ attempt.lossRate ?? 100 }}%</strong><span>失分率</span></div><div class="attempt-actions"><RouterLink v-if="attempt.overallStatus === 'IN_PROGRESS' && attempt.stageStatus === 'IN_PROGRESS'" :to="`/exam/take/${attempt.processId}`">继续答题</RouterLink><el-button text type="primary" :loading="analysisLoading === attempt.processId" @click="showAnalysis(attempt)">查看分析</el-button></div></article></div><div v-else class="empty-state">完成答题后，这里会显示得分与人工智能综合评价。</div></section>
    <el-dialog v-model="analysisVisible" title="人工智能学习分析" width="min(680px, calc(100vw - 28px))"><div class="analysis-summary"><div><span>得分率</span><strong>{{ selectedAnalysis.scoreRate || 0 }}%</strong></div><div><span>失分率</span><strong>{{ selectedAnalysis.lossRate || 0 }}%</strong></div><div><span>有效答题</span><strong>{{ selectedAnalysis.answeredRounds || 0 }} 轮</strong></div></div><p class="analysis-copy">{{ selectedAnalysis.aiSummary }}</p><el-table :data="selectedAnalysis.knowledgePoints || []"><el-table-column prop="knowledgePoint" label="知识点" /><el-table-column label="得分率"><template #default="{row}">{{ row.scoreRate }}%</template></el-table-column><el-table-column label="失分率"><template #default="{row}">{{ row.lossRate }}%</template></el-table-column><el-table-column prop="rounds" label="答题数" /></el-table></el-dialog>
  </main>
</template>

<script setup>
import { onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { RouterLink, useRouter } from 'vue-router'
import { authApi, schoolApi } from '../services/api'

const router = useRouter(); const session = reactive({ displayName: '' }); const exams = ref([]); const attempts = ref([]); const loading = ref(false); const startingId = ref(null); const analysisVisible = ref(false); const analysisLoading = ref(null); const selectedAnalysis = reactive({})
function dateText(value) { return value ? String(value).replace('T', ' ').slice(0, 16) : '不限' }; function stateText(attempt) { return attempt.overallStatus === 'IN_PROGRESS' ? '答题进行中' : '答题已完成' }
async function load() { loading.value = true; try { const [user, available, history] = await Promise.all([authApi.getSession(), schoolApi.listStudentExams(), schoolApi.listStudentAttempts()]); Object.assign(session, user.data); exams.value = available.data || []; attempts.value = history.data || [] } catch (error) { ElMessage.error(error.message || '考试数据加载失败'); if (error.status === 401) router.push('/student/register') } finally { loading.value = false } }
async function start(exam) { startingId.value = exam.id; try { const response = await schoolApi.startExam(exam.id); router.push(`/exam/take/${response.data.processId}`) } catch (error) { ElMessage.error(error.message || '无法开始考试') } finally { startingId.value = null } }
async function showAnalysis(attempt) { analysisLoading.value = attempt.processId; try { Object.assign(selectedAnalysis, (await schoolApi.getAttemptAnalysis(attempt.processId)).data); analysisVisible.value = true } catch (error) { ElMessage.error(error.message || '学习分析生成失败') } finally { analysisLoading.value = null } }
async function logout() { try { await authApi.logout() } finally { router.push('/student/register') } }
onMounted(load)
</script>

<style scoped>
.student-page{max-width:1160px;margin:0 auto;padding:40px 28px}.student-head,.section-head{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.student-head{padding-bottom:32px;border-bottom:1px solid var(--border)}.student-head h1{margin:5px 0 8px;font-size:30px}.student-head p:not(.page-eyebrow){margin:0;color:var(--text-muted)}.head-actions{display:flex;gap:12px;align-items:center}.head-actions a{color:var(--primary);text-decoration:none}.section-head{align-items:center;margin:30px 0 14px}.section-head h2{margin:0;font-size:19px}.exam-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.exam-item{display:flex;min-height:265px;flex-direction:column;padding:20px;border:1px solid var(--border);border-radius:var(--radius-sm);background:var(--surface)}.exam-meta{display:flex;justify-content:space-between;color:var(--text-muted);font-size:12px}.exam-item h3{margin:20px 0 8px;font-size:20px}.exam-item p{margin:0;color:var(--ink-soft);line-height:1.6}.exam-item dl{display:grid;gap:7px;margin:auto 0 16px;padding-top:18px}.exam-item dl div{display:flex;justify-content:space-between;gap:12px;font-size:12px}.exam-item dt{color:var(--text-muted)}.exam-item dd{margin:0;text-align:right}.attempts{margin-top:36px}.attempt-list{display:grid;gap:10px}.attempt-item{display:grid;grid-template-columns:minmax(0,1fr) 100px 100px auto;gap:18px;align-items:center;padding:17px 0;border-bottom:1px solid var(--border)}.attempt-item h3{margin:0 0 5px;font-size:16px}.attempt-item p,.attempt-item span{margin:0;color:var(--text-muted);font-size:13px}.score strong,.score span{display:block}.score strong{font-size:22px}.attempt-actions{display:flex;gap:8px;align-items:center}.attempt-actions a{color:var(--primary);font-size:14px;text-decoration:none}.empty-state{padding:34px;border:1px dashed var(--border);color:var(--text-muted);text-align:center}.analysis-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.analysis-summary div{padding:14px 0;border-bottom:2px solid #d8e4e1}.analysis-summary span,.analysis-summary strong{display:block}.analysis-summary span{color:var(--text-muted);font-size:13px}.analysis-summary strong{margin-top:6px;font-size:23px}.analysis-copy{line-height:1.75;color:var(--ink-soft)}@media(max-width:860px){.student-page{padding:24px 16px}.exam-grid{grid-template-columns:1fr}.attempt-item{grid-template-columns:1fr 1fr}.attempt-actions{grid-column:1/-1}.student-head{flex-direction:column}.analysis-summary{grid-template-columns:1fr}}
</style>
